feat: record dry-run power decisions

diff --git a/package/zte-usb-wifi-manager/files/usr/sbin/zte-usb-wifi-managerd b/package/zte-usb-wifi-manager/files/usr/sbin/zte-usb-wifi-managerd
--- a/package/zte-usb-wifi-manager/files/usr/sbin/zte-usb-wifi-managerd
+++ b/package/zte-usb-wifi-manager/files/usr/sbin/zte-usb-wifi-managerd
@@ -7,6 +7,7 @@ set -e
 . /usr/lib/zte-usb-wifi-manager/http.sh
 . /usr/lib/zte-usb-wifi-manager/session.sh
 . /usr/lib/zte-usb-wifi-manager/policy.sh
+. /usr/lib/zte-usb-wifi-manager/power-adapter.sh
 . /usr/lib/zte-usb-wifi-manager/snapshot.sh
 . /usr/lib/zte-usb-wifi-manager/netifd-adapter.sh
 . /usr/lib/zte-usb-wifi-manager/adapter-zte-u25s-metadata.sh
@@ -28,6 +29,7 @@ load_config() {
 	battery_enabled=''
 	battery_low=''
 	battery_high=''
+	power_backend=''
 
 	config_load zte-usb-wifi-manager
 	config_get enabled main enabled 1
@@ -41,6 +43,7 @@ load_config() {
 	config_get battery_enabled policy enabled 0
 	config_get battery_low policy low_percent 70
 	config_get battery_high policy high_percent 100
+	config_get power_backend usb backend unconfigured
 
 	zte_validate_host "$host" || {
 		logger -t zte-usb-wifi-manager 'invalid device host'
@@ -68,6 +71,10 @@ load_config() {
 		logger -t zte-usb-wifi-manager 'invalid battery thresholds'
 		return 1
 	}
+	zte_power_backend_valid "$power_backend" || {
+		logger -t zte-usb-wifi-manager 'invalid power backend'
+		return 1
+	}
 }
 
 init_state() {
@@ -91,6 +98,35 @@ collect_network() {
 		network_json=$(zte_netifd_collect "$interface" "$netdev")
 	else
 		network_json=$(zte_netifd_json 0 "$netdev" '' '' 0)
+	fi
+}
+
+apply_policy_action() {
+	_zte_policy_state=$1
+	_zte_policy_action=$2
+
+	case $power_backend in
+		mock|dry-run) ;;
+		*) return 0 ;;
+	esac
+	[ "$_zte_policy_action" != KEEP ] || return 0
+	[ "$_zte_policy_action" != "$last_power_action" ] || return 0
+
+	case $_zte_policy_state in
+		MAINTAIN_CHARGING) _zte_power_reason=battery_low ;;
+		MAINTAIN_BATTERY) _zte_power_reason=battery_high ;;
+		MANUAL_FULL) _zte_power_reason=manual_full ;;
+		PRE_DEPARTURE) _zte_power_reason=pre_departure ;;
+		FAIL_SAFE_ON) _zte_power_reason=fail_safe ;;
+		*) return 0 ;;
+	esac
+
+	if zte_power_apply \
+		"$power_backend" "$_zte_policy_action" "$_zte_power_reason" \
+		"$STATE_DIR/power-decision.json" >/dev/null; then
+		last_power_action=$_zte_policy_action
+	else
+		logger -t zte-usb-wifi-manager 'power decision recording failed'
 	fi
 }
 
@@ -143,13 +179,21 @@ poll_once() {
 	power_action=none
 	if [ "$ok" = 1 ]; then
 		battery_percent=$(zte_json_path_get "$device_json" battery percent)
+		battery_charging=$(zte_json_path_get "$device_json" battery charging)
+		case $battery_charging in
+			true) current_power=ON ;;
+			false) current_power=OFF ;;
+			*) current_power=UNKNOWN ;;
+		esac
 		if zte_is_uint "$battery_percent"; then
 			policy_result=$(zte_policy_decide \
 				"$battery_enabled" 0 0 0 "$battery_percent" \
-				"$battery_low" "$battery_high" UNKNOWN) || policy_result=''
+				"$battery_low" "$battery_high" "$current_power") ||
+				policy_result=''
 			if [ -n "$policy_result" ]; then
 				policy_state=${policy_result%%:*}
 				power_action=${policy_result#*:}
+				apply_policy_action "$policy_state" "$power_action"
 			fi
 		fi
 	fi
@@ -166,6 +210,7 @@ main() {
 	init_state
 	failures=0
 	last_device_json=''
+	last_power_action=''
 	while [ "$enabled" = 1 ]; do
 		poll_once
 		sleep "$(zte_backoff_interval "$poll_interval" "$failures")"
